# Generated by Django 5.1.6 on 2025-04-18 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=200)),
                ('training_type', models.CharField(choices=[('musculation', 'Musculation'), ('cardio', 'Cardio'), ('yoga', 'Yoga'), ('hiit', 'HIIT'), ('pilates', 'Pilates'), ('mobilité', 'Mobilité'), ('circuit training', 'Circuit Training'), ('running', 'Running'), ('streetlifting', 'Streetlifting')], max_length=200)),
                ('training_duration', models.IntegerField()),
                ('training_calories', models.IntegerField()),
                ('training_date', models.DateField()),
                ('goal', models.TextField()),
                ('level', models.CharField(choices=[('Débutant', 'Débutant'), ('Intermédiaire', 'Intermédiaire'), ('Avancé', 'Avancé'), ('Tous niveaux', 'Tous niveaux')], max_length=200)),
            ],
            options={
                'db_table': 'training',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='female', max_length=10)),
                ('is_connected', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
