# Generated by Django 5.1.6 on 2025-04-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=200)),
                ('training_type', models.CharField(max_length=200)),
                ('training_duration', models.IntegerField()),
                ('training_calories', models.IntegerField()),
                ('training_date', models.DateField()),
            ],
        ),
    ]
