# Generated by Django 5.1.6 on 2025-04-16 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_training'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'managed': False},
        ),
    ]
