# Generated by Django 5.1.6 on 2025-04-21 14:30

import uuid
from django.db import migrations, models

def generate_uuids(apps, schema_editor):
    Profile = apps.get_model('myapp', 'Profile')
    for profile in Profile.objects.all():
        profile.uuid = uuid.uuid4()
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_profile_bmi_profile_daily_calories_estimate_and_more'),
    ]

    operations = [
migrations.AddField(
    model_name='profile',
    name='uuid',
    field=models.UUIDField(default=None, null=True, unique=True),
),
migrations.RunPython(generate_uuids),
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
