# Generated by Django 5.1.6 on 2025-04-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_profile_friends'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'managed': True},
        ),
    ]
