# Generated by Django 5.1.6 on 2025-04-22 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_training_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='myapp.profile'),
        ),
    ]
